language: java
jdk: oraclejdk8
install: true
script: mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: qvaxSrdx2axj8T56qi/XgYxkn8aEVkSL6VpNd3cAAh0tL6Hl1cxyxhj2nVbfb5uZLAIaRi3/nMuAWn0g3zeqmfHVabYf7t5zweDhYsS8D8AshJlzW/0X5zfuSXnUnlNhJ2T6dMDQg9kXV8fqZ9IGbZ0Pa4/Pu3eqBLFbt5eiwmvyH8BRZkqb4AItPmf7qpa9qqto1UuL7Ke2rNS9CnMDXuDLPBdvW6JuaOPlgohU4Ez0lGpiOxt7Zf2t3MlOnb37KGdG8gTIYCFo7+yIH2CaUXLgeWPcxb+7/wf357746eY+1pJSOdbMKR5nSPPpfs7bCJXbBhQbP90qKApyotaoEdeIawPdfYIz11bb3jiM9oYS9wZWwI7YxKroB6d3iBR8WgGPenCJ+gnAsO2n1y127NrBqgFJLaoxyb87hVKwfm9b63xNW8O57o/phgKvenfBD6sFOsWTT291Nc7f9oAxxXP0HzzfFBB9cepPtWD5kkeUfIB6Gt8HnmhyRfsdqyO1J7F6pWf/gOmn4o5ldlxd1D2EfsbfGKJ7GW/CNjxob63t31sjh/YG6aRzEW3nLgYugjS6BEsJdO2ZsSEtimlEZx/gNhwZgaK20V2A2QemiNTjJX4kE4lxt4REO21z3P3SDtAx22VmCaF0dZodba9CU79H20emyGIZjGV3q67OyZU=
  app: AxxesTime
